// <autogenerated>
//   This file was generated by T4 code generator MyTest.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

namespace T4Demo.T4Tool
{
	public class Course
	{
        public int CourseId{ get; set; }		
        public string CourseName{ get; set; }		
        public string Location{ get; set; }		
        public int TeacherId{ get; set; }		
    }
}
